#!/usr/bin/env python3
"""
Scan existing skills and auto-tag by scope + dependencies.
Generates SKILL_REGISTRY.md with metadata.
"""
import os
import re
import sys
from pathlib import Path
from collections import defaultdict
from datetime import datetime, timezone

sys.path.insert(0, str(Path(__file__).parent))
try:
    from incident_detector import Incident, IncidentType, IncidentSeverity
    from finding_creator import FindingCreator
    from opensre_findings_format import OpenSREFindingsExporter
    HAS_FINDINGS = True
except ImportError:
    HAS_FINDINGS = False

REPO_ROOT = Path("/opt/YOUR-PROJECT")

# Skill directory locations
SKILL_DIRS = [
    ("agents/skills", "jeanne"),
    ("agents/vendors/agent-skills/skills", "anthropic"),
    ("agents/vendors/mattpocock-skills/skills", "mattpocock"),
    ("agents/vendors/ruflo-skills", "ruflo"),
]

# Scope tagging rules (keywords → scope)
SCOPE_KEYWORDS = {
    "code": ["review", "refactor", "simplify", "quality", "test", "tdd", "debug"],
    "security": ["security", "audit", "vulnerability", "threat", "permission"],
    "memory": ["memory", "recall", "embedding", "retrieval", "context"],
    "infra": ["docker", "systemd", "deploy", "cron", "bash", "ops"],
    "ai": ["inference", "model", "prompt", "ollama", "routing"],
    "content": ["document", "adr", "wiki", "runbook", "guide"],
    "agent": ["agent", "task", "planning", "orchestrat", "workflow"],
}

def extract_first_line(md_path):
    """Extract first non-heading line from SKILL.md."""
    try:
        with open(md_path) as f:
            for line in f:
                line = line.strip().lstrip("#").strip()
                if line and not line.startswith("---"):
                    return line[:100]
    except:
        pass
    return ""

def detect_scope(skill_name, description):
    """Auto-detect skill scope from name and description."""
    combined = f"{skill_name} {description}".lower()
    scopes = set()
    for scope, keywords in SCOPE_KEYWORDS.items():
        if any(kw in combined for kw in keywords):
            scopes.add(scope)
    return list(scopes) if scopes else ["general"]

def scan_skills():
    """Scan all skills and return list of (name, source, scope, description)."""
    skills = []

    for skill_dir, source in SKILL_DIRS:
        path = REPO_ROOT / skill_dir
        if not path.exists():
            continue

        for entry in sorted(path.iterdir()):
            if not entry.is_dir():
                continue

            # Look for SKILL.md or skill.md
            manifest = entry / "SKILL.md"
            if not manifest.exists():
                manifest = entry / "skill.md"
            if not manifest.exists():
                continue

            name = entry.name
            desc = extract_first_line(manifest)
            scopes = detect_scope(name, desc)

            skills.append({
                "name": name,
                "source": source,
                "description": desc,
                "scopes": scopes,
                "path": str(manifest),
            })

    return skills

def generate_registry_md(skills):
    """Generate SKILL_REGISTRY.md content."""
    lines = [
        "# SKILL_REGISTRY.md — Metadata Index of All Available Skills",
        "",
        "**Auto-generated by ops/agent/scan_skills.py**",
        "",
        "This registry provides metadata for all skills available to agents:",
        "- Source (jeanne vs vendor)",
        "- Scope tags (code, security, memory, infra, ai, content, agent)",
        "- One-line description",
        "- File path for lookup",
        "",
        "---",
        "",
        "## Scope Tags Reference",
        "",
        "| Scope | Meaning | Example |",
        "|-------|---------|---------|",
        "| **code** | Code quality, refactoring, testing | review, simplify, test-driven |",
        "| **security** | Security auditing, threat analysis | audit, vulnerability, permission |",
        "| **memory** | Persistent intelligence, retrieval | embedding, context, recall |",
        "| **infra** | Infrastructure, ops, deployment | docker, systemd, deploy |",
        "| **ai** | AI inference, model selection | ollama, routing, prompt |",
        "| **content** | Documentation, knowledge | adr, runbook, guide |",
        "| **agent** | Agent orchestration, planning | planning, workflow, task |",
        "| **general** | Unclassified | (catch-all) |",
        "",
        "---",
        "",
        "## Skills by Source",
        "",
    ]

    # Group by source
    by_source = defaultdict(list)
    for skill in sorted(skills, key=lambda s: s["name"]):
        by_source[skill["source"]].append(skill)

    for source in ["jeanne", "anthropic", "mattpocock", "ruflo"]:
        if source not in by_source:
            continue

        lines.append(f"### {source.upper()}")
        lines.append("")

        for skill in by_source[source]:
            scopes_str = ", ".join(f"`{s}`" for s in skill["scopes"])
            lines.append(f"- **{skill['name']}** [{scopes_str}]")
            lines.append(f"  {skill['description']}")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## All Skills (Alphabetical)")
    lines.append("")
    lines.append("| Name | Source | Scopes | Description |")
    lines.append("|------|--------|--------|-------------|")

    for skill in sorted(skills, key=lambda s: s["name"]):
        scopes_str = ", ".join(skill["scopes"])
        desc = skill["description"][:60]
        lines.append(f"| {skill['name']} | {skill['source']} | {scopes_str} | {desc} |")

    return "\n".join(lines)

if __name__ == "__main__":
    skills = scan_skills()
    print(f"Found {len(skills)} skills")

    registry_content = generate_registry_md(skills)

    # Write to file
    registry_path = REPO_ROOT / "agents" / "SKILL_REGISTRY.md"
    registry_path.write_text(registry_content)
    print(f"✅ Created {registry_path}")
    print(f"   {len(registry_content)} bytes")
